//Question 1
console.log(2*3+1); //it will display 7
console.log(2**4); //it wii give us 16
console.log(5*1); //it will display 5
console.log(8**2-5**2), //it will  display 39
// ANSWER OF Q2
console.log(4*5==20);
console.log(6*5==30);
console.log(-17<0);
console.log(25>1);
console.log(2+2*2>4);
// ANSWER OF Q3
console.log(true ||false);//it wii be true
console.log(!false && false);//it wii be true
console.log(false&&false||true); //it will be true
console.log(true&&false||false&&true);//it will be true
